# Reasoning Engine Configuration
# Focused on pure LLM-based tool selection and argument extraction

llm:
  model: "gpt-oss:20b"
  provider: "ollama" 
  api_url: "http://localhost:11434/api/generate"
  timeout: 10
  options:
    temperature: 0.0
    top_p: 1.0

reasoning:
  system_prompt_template: |
    You are an AI assistant that creates step-based execution plans for tools.
    
    Available tools:
    {tools}
    
    Your task is to create an ordered plan where each step is a tool with its arguments and reasoning.
    The steps will be executed in sequence. Parse the query and create the execution plan.
    
    IMPORTANT RULES:
    - Tool names must match exactly from the list above
    - If required parameters are missing from the query, use placeholder values
    - Each step must include a 'why' field explaining the reasoning
    - Return a JSON object with 'plan' array and 'confidence' number
  
  user_prompt_template: "User query: {query}"

# JSON Schema for step-based plan format
json_schema:
  type: "object"
  properties:
    plan:
      type: "array"
      items:
        type: "object"
        properties:
          tool:
            type: "string"
            description: "Name of the tool to execute"
          arguments:
            type: "object"
            description: "Arguments for the tool"
          why:
            type: "string"
            description: "Explanation of why this step is needed"
        required: ["tool", "arguments", "why"]
      description: "Ordered list of execution steps"
      minItems: 1
    confidence:
      type: "number"
      description: "Confidence level in the execution plan"
      minimum: 0.0
      maximum: 1.0
  required: ["plan", "confidence"]

response_format:
  include_confidence: true
  include_reasoning: true
  max_tools_per_query: 5 